///////////////////////////////////////
// Imports
///////////////////////////////////////
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

// Mui Imports
import Header from './Header'
import Sidebar from './Sidebar'

import FormControl from '@mui/material/FormControl';
import FormHelperText from '@mui/material/FormControl';
import Container from '@mui/material/Container';
import Input from '@mui/material/Input';
import InputLabel from '@mui/material/InputLabel';
import Button from '@mui/material/Button';

const inter = Inter({ subsets: ['latin'] })

///////////////////////////////////////
// Home function
///////////////////////////////////////
export default function Home() {
  return (
    <>
      {/* Head tag */}
      <Head>
        <title>To-Do List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/* Main content */}
      <main>
        
        {/* 1.) Header */}
        {/* <Header/> */}
        

        {/* 2.) Side bar */}
        <Sidebar/>

        {/* 3.) Content */}
        <div className="to-do-add-form">
          {/* 
          <FormControl>
            <InputLabel htmlFor="my-input">Email address</InputLabel>
            <Input id="my-input" aria-describedby="my-helper-text" />
            <FormHelperText id="my-helper-text">We'll never share your email.</FormHelperText>
            <Button>Submit</Button>
          </FormControl> 
          */}
          <form>
            <h3>Add task</h3>
            <input type="text"></input>
            <button type="submit">Add</button>
            {/* <Button type="submit" variant="outlined">Submit</Button> */}
          </form>
        
        </div>  
        <div className="to-do-item">
          {/* <Container fixed style={{backgroundColor: "grey"}}>Todo element 1</Container> */}
        </div>
        
      </main>
    </>
  )
}
