///////////////////////////////////////
// Imports
///////////////////////////////////////
import * as React from 'react';
import Head from 'next/head'
import Image from 'next/image'
import { Inter, Roboto } from 'next/font/google'

// Codehooks imports
// import {app, Datastore} from 'codehooks-js';

const inter = Inter({ subsets: ['latin'] })

const roboto = Roboto({
  weight: '900',
  subsets: ['latin'],
})

///////////////////////////////////////
// Home function
///////////////////////////////////////
export default function Home() {
  
  // --------------------------------
  // ----- Return JSX statement -----
  // --------------------------------
  return (
    <>
      {/* Head tag */}
      <Head>
        <title>To-Do List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/* Main content */}
      <main className={inter.className}>
        
      </main>
    </>
  )
}
